// =============================================
// GEKA STORE - CENTRALIZED PRODUCT DATA
// =============================================
const PRODUCTS = [
    // ---- LAPIS TALAS BOGOR ----
    {
        id: 'lapis-talas-original',
        name: 'Lapis Talas Bogor Original',
        category: 'Lapis Talas Bogor',
        price: 38000,
        originalPrice: 45000,
        stock: 50,
        rating: 4.8,
        reviews: 124,
        sold: 320,
        images: [
            'https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775358042/yuton17knzkrclbeo5pp.jpg',
            'https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775358042/yuton17knzkrclbeo5pp.jpg',
            'https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775358042/yuton17knzkrclbeo5pp.jpg',
        ],
        description: 'Bolu Lapis Talas Bogor Original hadir dengan tekstur lembut dan padat yang khas. Dibuat dari talas pilihan asli Bogor yang menghadirkan aroma dan cita rasa autentik di setiap lapisannya.',
        specs: { berat: '300g', ukuran: '20x10x8 cm', ketahanan: '3 hari suhu ruang / 7 hari kulkas', varian: ['Original', 'Keju', 'Brownies'] },
        tags: ['oleh-oleh', 'bogor', 'lapis', 'talas'],
        waNumber: '6287885038485'
    },
    {
        id: 'lapis-talas-brownies',
        name: 'Lapis Talas Bogor Brownies',
        category: 'Lapis Talas Bogor',
        price: 40000,
        originalPrice: 48000,
        stock: 45,
        rating: 4.7,
        reviews: 98,
        sold: 210,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775358042/yuton17knzkrclbeo5pp.jpg'],
        description: 'Perpaduan sempurna antara lapis talas lembut khas Bogor dengan kekayaan rasa cokelat brownies. Menghadirkan sensasi dua cita rasa dalam satu gigitan yang lezat.',
        specs: { berat: '300g', ukuran: '20x10x8 cm', ketahanan: '3 hari suhu ruang', varian: ['Brownies', 'Brownies Keju'] },
        tags: ['oleh-oleh', 'brownies', 'coklat'],
        waNumber: '6287885038485'
    },
    {
        id: 'lapis-talas-keju',
        name: 'Lapis Talas Bogor Keju',
        category: 'Lapis Talas Bogor',
        price: 42000,
        originalPrice: null,
        stock: 40,
        rating: 4.9,
        reviews: 77,
        sold: 180,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775358042/yuton17knzkrclbeo5pp.jpg'],
        description: 'Lapis talas dengan taburan keju cheddar melimpah yang gurih dan menggugah selera. Perpaduan manis talas dan gurihnya keju menciptakan harmoni rasa yang sempurna.',
        specs: { berat: '320g', ukuran: '20x10x8 cm', ketahanan: '3 hari suhu ruang', varian: ['Keju Cheddar', 'Keju Mozarella'] },
        tags: ['keju', 'gurih', 'lapis'],
        waNumber: '6287885038485'
    },
    {
        id: 'lapis-talas-full',
        name: 'Lapis Talas Bogor Full Talas',
        category: 'Lapis Talas Bogor',
        price: 45000,
        originalPrice: null,
        stock: 35,
        rating: 4.9,
        reviews: 55,
        sold: 140,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775358042/yuton17knzkrclbeo5pp.jpg'],
        description: 'Versi full talas dengan komposisi talas yang lebih banyak, menghasilkan tekstur lebih padat dan aroma talas yang lebih kuat dan autentik.',
        specs: { berat: '350g', ukuran: '20x10x8 cm', ketahanan: '3 hari suhu ruang', varian: ['Full Talas'] },
        tags: ['full talas', 'padat', 'autentik'],
        waNumber: '6287885038485'
    },
    // ---- BOLU SUSU MADU ----
    {
        id: 'bolu-susu-madu-coklat',
        name: 'Coklat Susu Bolu Susu Madu',
        category: 'Bolu Susu Madu',
        price: 37000,
        originalPrice: null,
        stock: 100,
        rating: 4.7,
        reviews: 201,
        sold: 450,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775357468/srqjjk48kvk7vdvwvyrh.jpg'],
        description: 'Bolu Susu Madu varian coklat hadir dengan perpaduan kelembutan bolu susu dan manisnya madu pilihan yang berpadu dalam alunan rasa coklat premium.',
        specs: { berat: '250g', ukuran: '15x10x6 cm', ketahanan: '5 hari suhu ruang', varian: ['Coklat', 'Coklat Keju'] },
        tags: ['coklat', 'madu', 'bolu'],
        waNumber: '6287885038485'
    },
    {
        id: 'bolu-susu-madu-vanila',
        name: 'Vanila Susu Bolu Susu Madu',
        category: 'Bolu Susu Madu',
        price: 37000,
        originalPrice: null,
        stock: 100,
        rating: 4.6,
        reviews: 155,
        sold: 380,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775357468/srqjjk48kvk7vdvwvyrh.jpg'],
        description: 'Bolu Susu Madu varian vanila dengan aroma vanilla yang harum dan lembut. Paduan sempurna antara kelembutan bolu dan manisnya madu asli.',
        specs: { berat: '250g', ukuran: '15x10x6 cm', ketahanan: '5 hari suhu ruang', varian: ['Vanila', 'Vanila Keju'] },
        tags: ['vanila', 'madu', 'lembut'],
        waNumber: '6287885038485'
    },
    {
        id: 'bolu-susu-madu-avocado',
        name: 'Avocado Bolu Susu Khas Lembang',
        category: 'Bolu Susu Madu',
        price: 38000,
        originalPrice: null,
        stock: 80,
        rating: 4.8,
        reviews: 133,
        sold: 290,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775357468/srqjjk48kvk7vdvwvyrh.jpg'],
        description: 'Bolu susu khas Lembang dengan sentuhan alpukat segar. Rasa creamy alpukat yang khas berpadu dengan kelembutan bolu dan aroma harum susu Lembang.',
        specs: { berat: '260g', ukuran: '15x10x6 cm', ketahanan: '3 hari suhu ruang', varian: ['Alpukat', 'Alpukat Madu'] },
        tags: ['alpukat', 'creamy', 'lembang'],
        waNumber: '6287885038485'
    },
    // ---- PIE SUSU ----
    {
        id: 'pie-susu-original',
        name: 'Pie Susu Lembang Original',
        category: 'Pie Susu',
        price: 35000,
        originalPrice: null,
        stock: 30,
        rating: 4.7,
        reviews: 88,
        sold: 220,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775363301/yqy1hjkqhizbb0soq0fy.png'],
        description: 'Pie susu khas Lembang dengan kulit pie renyah dan isian susu yang manis, creamy, dan lembut. Perpaduan tekstur yang memukau di setiap suapan.',
        specs: { berat: '200g', ukuran: 'Isi 10 pcs', ketahanan: '2 hari suhu ruang', varian: ['Original', 'Keju', 'Coklat'] },
        tags: ['pie', 'susu', 'renyah'],
        waNumber: '6287885038485'
    },
    // ---- BOLU SUSU ----
    {
        id: 'bolu-susu-original',
        name: 'Bolu Susu Khas Lembang Original',
        category: 'Bolu Susu',
        price: 32000,
        originalPrice: null,
        stock: 60,
        rating: 4.6,
        reviews: 175,
        sold: 390,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775357049/zdxupjv1qmqbh3btekrx.jpg'],
        description: 'Bolu susu lembut khas Lembang dengan rasa susu autentik yang kaya. Dibuat dari susu sapi pilihan Lembang yang memberikan cita rasa unik dan lembut.',
        specs: { berat: '220g', ukuran: '18x8x6 cm', ketahanan: '4 hari suhu ruang', varian: ['Original', 'Keju', 'Coklat', 'Pandan'] },
        tags: ['bolu', 'susu', 'lembang'],
        waNumber: '6287885038485'
    },
    {
        id: 'bolu-susu-keju',
        name: 'Bolu Susu Keju Lembang',
        category: 'Bolu Susu',
        price: 35000,
        originalPrice: null,
        stock: 55,
        rating: 4.8,
        reviews: 142,
        sold: 310,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775357049/zdxupjv1qmqbh3btekrx.jpg'],
        description: 'Bolu susu Lembang dengan taburan keju cheddar premium yang melimpah. Gurihnya keju berpadu sempurna dengan kelembutan bolu susu yang autentik.',
        specs: { berat: '240g', ukuran: '18x8x6 cm', ketahanan: '4 hari suhu ruang', varian: ['Keju Cheddar', 'Triple Keju'] },
        tags: ['keju', 'gurih', 'premium'],
        waNumber: '6287885038485'
    },
    // ---- BAKPIA ----
    {
        id: 'bakpia-original',
        name: 'Bakpia Pathok Original',
        category: 'Bakpia Khas Jogja',
        price: 30000,
        originalPrice: null,
        stock: 40,
        rating: 4.5,
        reviews: 66,
        sold: 160,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775363415/wmgozpn86vtqiau8i1oz.png'],
        description: 'Bakpia pathok khas Jogja dengan isian kacang hijau yang legit, lembut, dan tidak terlalu manis. Kulit tipis renyah dengan tekstur isian yang padat berkualitas.',
        specs: { berat: '350g', ukuran: 'Isi 20 pcs', ketahanan: '5 hari suhu ruang', varian: ['Kacang Hijau', 'Coklat', 'Keju', 'Durian'] },
        tags: ['bakpia', 'jogja', 'oleh-oleh'],
        waNumber: '6287885038485'
    },
    // ---- TIRAMISU ----
    {
        id: 'tiramisu-original',
        name: 'Tiramisu Coklat Lumer Original',
        category: 'Tiramisu Coklat Lumer',
        price: 45000,
        originalPrice: 55000,
        stock: 25,
        rating: 4.9,
        reviews: 89,
        sold: 200,
        images: ['https://res.cloudinary.com/dtqrp1ydo/image/upload/v1775358861/nm7sr2zwwtkviwpt6dhv.jpg'],
        description: 'Tiramisu premium dengan lapisan coklat ganache yang lumer dan creamy. Perpaduan kopi, coklat, dan mascarpone pilihan menghadirkan pengalaman dessert kelas atas.',
        specs: { berat: '400g', ukuran: '20x15x6 cm', ketahanan: '3 hari kulkas', varian: ['Original', 'Matcha', 'Strawberry'] },
        tags: ['tiramisu', 'premium', 'lumer'],
        waNumber: '6287885038485'
    },
    // ============================================
    // ---- WOMEN CATEGORY ----
    // ============================================
    {
        id: 'women-dress-floral',
        name: 'Floral Maxi Dress Premium',
        category: 'WOMEN',
        subCategory: 'Baju Wanita',
        price: 185000,
        originalPrice: 250000,
        stock: 30,
        rating: 4.8,
        reviews: 203,
        sold: 512,
        images: [
            'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&q=80',
            'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&q=80',
        ],
        description: 'Floral Maxi Dress dengan motif bunga elegan yang cocok untuk berbagai acara. Dibuat dari bahan premium yang lembut, ringan, dan mudah dirawat. Potongan A-line yang flattering untuk semua bentuk tubuh.',
        specs: { bahan: 'Viscose Twill', ukuran: 'S / M / L / XL / XXL', warna: ['Floral Pink', 'Floral Blue', 'Floral Green'], perawatan: 'Cuci dingin, jangan diperas' },
        tags: ['dress', 'floral', 'maxi', 'wanita'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Floral Pink', 'Floral Blue', 'Floral Green'],
        waNumber: '6287885038485'
    },
    {
        id: 'women-blouse-casual',
        name: 'Casual Linen Blouse Wanita',
        category: 'WOMEN',
        subCategory: 'Baju Wanita',
        price: 135000,
        originalPrice: 175000,
        stock: 45,
        rating: 4.6,
        reviews: 167,
        sold: 378,
        images: [
            'https://images.unsplash.com/photo-1594938298603-c8148c4b5f2d?w=600&q=80',
            'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&q=80',
        ],
        description: 'Blouse linen kasual dengan desain minimalis modern. Material linen premium yang breathable dan nyaman dipakai seharian. Cocok dipadukan dengan celana, rok, maupun jeans.',
        specs: { bahan: 'Linen Premium', ukuran: 'S / M / L / XL', warna: ['White', 'Cream', 'Light Blue', 'Sage Green'], perawatan: 'Cuci tangan atau mesin cold' },
        tags: ['blouse', 'linen', 'kasual', 'wanita'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['White', 'Cream', 'Light Blue', 'Sage Green'],
        waNumber: '6287885038485'
    },
    {
        id: 'women-knit-cardigan',
        name: 'Knit Cardigan Oversize Women',
        category: 'WOMEN',
        subCategory: 'Baju Wanita',
        price: 215000,
        originalPrice: 280000,
        stock: 25,
        rating: 4.9,
        reviews: 315,
        sold: 720,
        images: [
            'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&q=80',
        ],
        description: 'Knit Cardigan oversize dengan rajutan halus yang hangat dan stylish. Potongan longgar memudahkan pergerakan dan cocok digunakan sebagai outer di segala musim.',
        specs: { bahan: 'Knit Acrylic Premium', ukuran: 'Free Size (fit S-XL)', warna: ['Cream', 'Brown', 'Grey', 'Olive'], perawatan: 'Dry clean direkomendasikan' },
        tags: ['cardigan', 'knit', 'oversize', 'outer'],
        sizes: ['Free Size'],
        colors: ['Cream', 'Brown', 'Grey', 'Olive'],
        waNumber: '6287885038485'
    },
    {
        id: 'women-highwaist-pants',
        name: 'High Waist Wide Leg Pants',
        category: 'WOMEN',
        subCategory: 'Baju Wanita',
        price: 165000,
        originalPrice: 210000,
        stock: 35,
        rating: 4.7,
        reviews: 228,
        sold: 490,
        images: [
            'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&q=80',
        ],
        description: 'High waist wide leg pants yang trendi dan profesional. Potongan wide leg dengan pinggang tinggi menciptakan siluet ramping dan elegan untuk tampilan casual maupun formal.',
        specs: { bahan: 'Woven Crepe', ukuran: 'XS / S / M / L / XL', warna: ['Black', 'Cream', 'Navy', 'Camel'], perawatan: 'Cuci dingin, gantung' },
        tags: ['celana', 'high waist', 'wide leg', 'trendi'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Black', 'Cream', 'Navy', 'Camel'],
        waNumber: '6287885038485'
    },
    {
        id: 'women-sneakers-white',
        name: 'Classic White Sneakers Women',
        category: 'WOMEN',
        subCategory: 'Sepatu Wanita',
        price: 325000,
        originalPrice: 420000,
        stock: 20,
        rating: 4.8,
        reviews: 445,
        sold: 890,
        images: [
            'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
            'https://images.unsplash.com/photo-1597248881519-db089d3744a5?w=600&q=80',
        ],
        description: 'Sneakers putih klasik yang timeless dan serbaguna. Cocok dipadukan dengan outfit apapun dari kasual hingga semi-formal. Sol cushioning yang nyaman untuk pemakaian seharian.',
        specs: { material: 'Canvas + Rubber Sole', ukuran: '36 / 37 / 38 / 39 / 40', warna: ['White', 'White/Black'], tinggiSol: '3 cm' },
        tags: ['sneakers', 'putih', 'kasual', 'sepatu'],
        sizes: ['36', '37', '38', '39', '40'],
        colors: ['White', 'White/Black'],
        waNumber: '6287885038485'
    },
    {
        id: 'women-heels-black',
        name: 'Block Heels Formal Women',
        category: 'WOMEN',
        subCategory: 'Sepatu Wanita',
        price: 285000,
        originalPrice: 350000,
        stock: 15,
        rating: 4.6,
        reviews: 187,
        sold: 340,
        images: [
            'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80',
        ],
        description: 'Block heels elegan untuk tampilan formal dan semi-formal. Desain block heel yang stabil dan nyaman dipakai seharian. Material kulit sintetis berkualitas tinggi yang tahan lama.',
        specs: { material: 'Synthetic Leather', ukuran: '36 / 37 / 38 / 39 / 40', warna: ['Black', 'Nude', 'Brown'], tinggiHak: '6 cm' },
        tags: ['heels', 'formal', 'elegan', 'sepatu'],
        sizes: ['36', '37', '38', '39', '40'],
        colors: ['Black', 'Nude', 'Brown'],
        waNumber: '6287885038485'
    },
    {
        id: 'women-sandal-platform',
        name: 'Platform Sandal Trendy',
        category: 'WOMEN',
        subCategory: 'Sepatu Wanita',
        price: 195000,
        originalPrice: 250000,
        stock: 22,
        rating: 4.7,
        reviews: 264,
        sold: 530,
        images: [
            'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&q=80',
        ],
        description: 'Platform sandal trendi dengan platform tebal yang memberikan tambahan tinggi. Desain tali yang adjustable untuk kenyamanan optimal dan tampilan yang stylish di berbagai acara kasual.',
        specs: { material: 'PU Leather + EVA Platform', ukuran: '36 / 37 / 38 / 39 / 40', warna: ['Black', 'Tan', 'White'], tinggiPlatform: '5 cm' },
        tags: ['sandal', 'platform', 'trendi'],
        sizes: ['36', '37', '38', '39', '40'],
        colors: ['Black', 'Tan', 'White'],
        waNumber: '6287885038485'
    },
    {
        id: 'women-loafer-slip',
        name: 'Slip-On Loafer Women Casual',
        category: 'WOMEN',
        subCategory: 'Sepatu Wanita',
        price: 245000,
        originalPrice: null,
        stock: 28,
        rating: 4.5,
        reviews: 133,
        sold: 275,
        images: [
            'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=80',
        ],
        description: 'Slip-on loafer yang mudah dipakai dan dilepas. Desain klasik yang cocok untuk berbagai kesempatan dari kuliah hingga bekerja. Material suede imitasi yang premium dan mudah dirawat.',
        specs: { material: 'Suede Synthetic', ukuran: '36 / 37 / 38 / 39 / 40', warna: ['Black', 'Tan', 'Burgundy'] },
        tags: ['loafer', 'slip-on', 'kasual'],
        sizes: ['36', '37', '38', '39', '40'],
        colors: ['Black', 'Tan', 'Burgundy'],
        waNumber: '6287885038485'
    },
    // ============================================
    // ---- MEN CATEGORY ----
    // ============================================
    {
        id: 'men-polo-shirt',
        name: 'Premium Polo Shirt Men',
        category: 'MEN',
        subCategory: 'Baju Pria',
        price: 155000,
        originalPrice: 199000,
        stock: 50,
        rating: 4.7,
        reviews: 289,
        sold: 630,
        images: [
            'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80',
        ],
        description: 'Polo shirt premium dengan bahan pique cotton yang breathable dan nyaman. Desain clean dan elegan yang cocok digunakan untuk casual maupun smart casual. Jahitan rapi dan detail berkualitas tinggi.',
        specs: { bahan: 'Pique Cotton 220gsm', ukuran: 'S / M / L / XL / XXL', warna: ['Navy', 'White', 'Black', 'Grey', 'Maroon'], perawatan: 'Cuci mesin cold, jangan pemutih' },
        tags: ['polo', 'pria', 'cotton', 'smart casual'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Navy', 'White', 'Black', 'Grey', 'Maroon'],
        waNumber: '6287885038485'
    },
    {
        id: 'men-oxford-shirt',
        name: 'Oxford Button-Down Shirt Men',
        category: 'MEN',
        subCategory: 'Baju Pria',
        price: 195000,
        originalPrice: 249000,
        stock: 35,
        rating: 4.8,
        reviews: 198,
        sold: 420,
        images: [
            'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=600&q=80',
        ],
        description: 'Oxford button-down shirt klasik yang versatile. Bahan oxford cotton yang ringan namun tetap struktural. Cocok untuk formal, semi-formal, maupun casual dengan tampilan yang selalu rapi.',
        specs: { bahan: 'Oxford Cotton 180gsm', ukuran: 'S / M / L / XL / XXL', warna: ['White', 'Light Blue', 'Grey', 'Pink Pastel'], perawatan: 'Cuci dingin, setrika medium' },
        tags: ['kemeja', 'oxford', 'formal', 'pria'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['White', 'Light Blue', 'Grey', 'Pink Pastel'],
        waNumber: '6287885038485'
    },
    {
        id: 'men-jogger-pants',
        name: 'Slim Tapered Jogger Pants Men',
        category: 'MEN',
        subCategory: 'Baju Pria',
        price: 175000,
        originalPrice: 225000,
        stock: 40,
        rating: 4.6,
        reviews: 312,
        sold: 710,
        images: [
            'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80',
        ],
        description: 'Slim tapered jogger pants yang memadukan kenyamanan dan gaya. Potongan slim yang modern dengan detail drawstring dan karet di bagian bawah kaki memberikan tampilan sporty dan stylish.',
        specs: { bahan: 'French Terry Cotton', ukuran: 'S / M / L / XL / XXL', warna: ['Black', 'Grey', 'Olive', 'Navy'], perawatan: 'Cuci mesin, keringkan biasa' },
        tags: ['jogger', 'celana', 'sporty', 'pria'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Black', 'Grey', 'Olive', 'Navy'],
        waNumber: '6287885038485'
    },
    {
        id: 'men-hoodie-fleece',
        name: 'Fleece Zip Hoodie Men Premium',
        category: 'MEN',
        subCategory: 'Baju Pria',
        price: 285000,
        originalPrice: 360000,
        stock: 20,
        rating: 4.9,
        reviews: 456,
        sold: 980,
        images: [
            'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80',
        ],
        description: 'Fleece zip hoodie premium yang hangat dan nyaman. Bahan fleece berkualitas tinggi dengan lapisan dalam yang lembut. Zipper YKK berkualitas dan kantong kangaroo yang lebar.',
        specs: { bahan: 'Polar Fleece 320gsm', ukuran: 'S / M / L / XL / XXL / XXXL', warna: ['Black', 'Grey', 'Navy', 'Maroon'], perawatan: 'Cuci dingin, jangan dikeringkan mesin' },
        tags: ['hoodie', 'fleece', 'hangat', 'premium'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL', 'XXXL'],
        colors: ['Black', 'Grey', 'Navy', 'Maroon'],
        waNumber: '6287885038485'
    },
    {
        id: 'men-sneakers-running',
        name: 'Running Sneakers Men Sport',
        category: 'MEN',
        subCategory: 'Sepatu Pria',
        price: 395000,
        originalPrice: 499000,
        stock: 18,
        rating: 4.8,
        reviews: 503,
        sold: 1100,
        images: [
            'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
        ],
        description: 'Running sneakers pria dengan teknologi sole cushioning yang canggih. Ringan, responsif, dan mendukung aktivitas lari maupun olahraga sehari-hari. Upper mesh breathable menjaga kaki tetap segar.',
        specs: { material: 'Mesh Upper + Rubber Outsole', ukuran: '39 / 40 / 41 / 42 / 43 / 44', warna: ['Black/Red', 'White/Blue', 'Grey/Orange'] },
        tags: ['sneakers', 'running', 'sport', 'pria'],
        sizes: ['39', '40', '41', '42', '43', '44'],
        colors: ['Black/Red', 'White/Blue', 'Grey/Orange'],
        waNumber: '6287885038485'
    },
    {
        id: 'men-oxford-shoe',
        name: 'Classic Oxford Formal Shoes Men',
        category: 'MEN',
        subCategory: 'Sepatu Pria',
        price: 450000,
        originalPrice: 580000,
        stock: 12,
        rating: 4.7,
        reviews: 167,
        sold: 340,
        images: [
            'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=600&q=80',
        ],
        description: 'Oxford formal shoes klasik yang elegan dan profesional. Bahan kulit sapi asli yang akan semakin indah seiring waktu. Cocok untuk acara formal, wawancara kerja, maupun pernikahan.',
        specs: { material: 'Genuine Leather', ukuran: '39 / 40 / 41 / 42 / 43 / 44', warna: ['Black', 'Dark Brown', 'Tan'] },
        tags: ['oxford', 'formal', 'kulit', 'elegan'],
        sizes: ['39', '40', '41', '42', '43', '44'],
        colors: ['Black', 'Dark Brown', 'Tan'],
        waNumber: '6287885038485'
    },
    {
        id: 'men-slip-on-loafer',
        name: 'Casual Slip-On Loafer Men',
        category: 'MEN',
        subCategory: 'Sepatu Pria',
        price: 275000,
        originalPrice: 350000,
        stock: 25,
        rating: 4.6,
        reviews: 221,
        sold: 455,
        images: [
            'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&q=80',
        ],
        description: 'Kasual slip-on loafer yang stylish dan nyaman. Mudah dipakai untuk aktivitas sehari-hari dengan tampilan yang selalu rapi. Sole anti-slip yang aman di berbagai permukaan.',
        specs: { material: 'Suede Genuine', ukuran: '39 / 40 / 41 / 42 / 43 / 44', warna: ['Brown', 'Navy', 'Grey'] },
        tags: ['loafer', 'kasual', 'slip-on'],
        sizes: ['39', '40', '41', '42', '43', '44'],
        colors: ['Brown', 'Navy', 'Grey'],
        waNumber: '6287885038485'
    },
    {
        id: 'men-boots-ankle',
        name: 'Ankle Boots Leather Men',
        category: 'MEN',
        subCategory: 'Sepatu Pria',
        price: 520000,
        originalPrice: 650000,
        stock: 10,
        rating: 4.9,
        reviews: 144,
        sold: 280,
        images: [
            'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&q=80',
        ],
        description: 'Ankle boots kulit pria dengan desain maskulin dan modern. Bahan full-grain leather yang tahan lama dengan lapisan dalam yang nyaman. Dilengkapi zipper samping untuk kemudahan pemakaian.',
        specs: { material: 'Full-Grain Leather', ukuran: '39 / 40 / 41 / 42 / 43 / 44', warna: ['Black', 'Dark Brown'] },
        tags: ['boots', 'ankle', 'kulit', 'maskulin'],
        sizes: ['39', '40', '41', '42', '43', '44'],
        colors: ['Black', 'Dark Brown'],
        waNumber: '6287885038485'
    },
];

// Helper: get product by ID
function getProductById(id) {
    return PRODUCTS.find(p => p.id === id) || null;
}

// Helper: get products by category
function getProductsByCategory(category) {
    return PRODUCTS.filter(p => p.category === category);
}

// Helper: get related products (same category, exclude self)
function getRelatedProducts(product, limit = 4) {
    return PRODUCTS.filter(p => p.category === product.category && p.id !== product.id).slice(0, limit);
}

// Helper: format price
function formatPrice(price) {
    return 'Rp ' + price.toLocaleString('id-ID');
}
